version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
    command: npm test
    volumes:
      - ./test-results:/usr/src/app/test-results
