name: CI/CD con Docker

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Construir y correr las pruebas
      - name: Build Docker test image
        run: docker build -f Dockerfile.test -t carrito-tests .

      - name: Prepare test results folder
        run: mkdir -p test-results

      - name: Run container and execute tests
        run: docker run --rm \
              -v ${{ github.workspace }}/test-results:/usr/src/app/test-results \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -e GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }} \
              carrito-tests

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: test-results/results.json

      # Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir imagen de la app (producción)
      - name: Build production Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rau3:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/rau3:${{ github.sha }} .

      # Subir imagen a Docker Hub
      - name: Push production image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rau3:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rau3:${{ github.sha }}
