name: Correr Prueba con Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t carrito-tests .

      - name: Prepare test results folder
        run: mkdir -p test-results

      - name: Run container and execute tests
        run: docker run --rm -v ${{ github.workspace }}/test-results:/usr/src/app/test-results carrito-tests

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: test-results/results.json

      # 🔑 Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 📦 Volver a construir pero con el nombre correcto
      - name: Build Docker image with tag
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rau3:latest .

      # 🚀 Push a Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rau3:latest
